import { Schema, type, MapSchema, ArraySchema } from "@colyseus/schema";

export class Team extends Schema {
  /** Empty string for the bot team in solo mode. */
  @type("string") sessionId: string = "";
  @type("number") gold: number = 0;
  @type("number") mines: number = 0;
  /** Gold per second generated by mines. */
  @type("number") income: number = 0;
  /** "attack" | "hold" | "defend" */
  @type("string") command: string = "attack";
  @type("number") nextMineCost: number = 0;
}

export class Knight extends Schema {
  @type("string") team: string = "";
  @type("number") x: number = 0;
  @type("number") y: number = 0;
  @type("number") hp: number = 0;
  @type("number") maxHp: number = 0;
  @type("number") damage: number = 0;
  @type("number") attackSpeed: number = 0;
  @type("number") moveSpeed: number = 0;
  @type("number") armor: number = 0;
  @type("number") regen: number = 0;
  @type(["string"]) items = new ArraySchema<string>();
  @type("boolean") alive: boolean = true;
  /** Seconds until respawn; 0 when alive. */
  @type("number") respawnIn: number = 0;
}

export class Unit extends Schema {
  @type("string") team: string = "";
  @type("string") type: string = "";
  @type("number") x: number = 0;
  @type("number") y: number = 0;
  @type("number") hp: number = 0;
  @type("number") maxHp: number = 0;
}

export class Castle extends Schema {
  @type("string") team: string = "";
  @type("number") hp: number = 0;
  @type("number") maxHp: number = 0;
}

/** Client-relevant config values so the HUD never hardcodes numbers. */
export class ConfigSnapshot extends Schema {
  @type({ map: "number" }) itemPrices = new MapSchema<number>();
  @type({ map: "number" }) unitCosts = new MapSchema<number>();
  @type("number") maxItems: number = 4;
  @type("number") incomePerMine: number = 0;
  @type("number") unitKillReward: number = 0;
  @type("number") knightKillReward: number = 0;
}

export class MatchState extends Schema {
  @type("string") code: string = "xxxx";
  /** "waiting" | "playing" | "finished" */
  @type("string") phase: string = "waiting";
  /** "" | "blue" | "red" */
  @type("string") winner: string = "";
  @type({ map: Team }) teams = new MapSchema<Team>();
  @type({ map: Knight }) knights = new MapSchema<Knight>();
  @type({ map: Castle }) castles = new MapSchema<Castle>();
  /** Keyed by numeric-string unique id. */
  @type({ map: Unit }) units = new MapSchema<Unit>();
  @type(ConfigSnapshot) config = new ConfigSnapshot();
}
